---   #分割线  8091为生产环境 定义为prod   
server:
  port: 8091
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  profiles: prod  #生产环境
  application:    #定义服务名称
    name: provider-user
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: provider-user-8091                #定义微服务的名称
    prefer-ip-address: true                        #是否显示IP和端口
   
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.springcloud.pojo       #配置别名包路径
  mapper-locations: classpath:/mybatis/mappers/*.xml  #添加mapper映射文件
  configuration:
    map-underscore-to-camel-case: true                #开启驼峰映射规则

--- #8092为dev
server:
  port: 8092
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  profiles: dev  #研发环境
  application:    #定义服务名称
    name: provider-user
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: provider-user-8092                #定义微服务的名称
    prefer-ip-address: true                        #是否显示IP和端口
   
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.springcloud.pojo       #配置别名包路径
  mapper-locations: classpath:/mybatis/mappers/*.xml  #添加mapper映射文件
  configuration:
    map-underscore-to-camel-case: true                #开启驼峰映射规则